name: neurocard
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.18.4
  - python=3.7.7
  - pytorch==1.4.0
  - torchvision==0.5.0
  - psycopg2=2.8.4=py37h1ba5d50_0
  - pip
  - pip:
    - pandas==1.0.5
    - absl-py==0.9.0
    - glog==0.3.1
    - networkx==2.4
    - ray[tune]==0.8.7
    - tabulate==0.8.7
    - scipy==1.4.1
    - yapf==0.27.0
    - mako==1.1.3
    - pyspark==2.4.3
    - wandb==0.8.36
    - pyarrow
